<h1 style = "color : deepskyblue"> Numpy </h1>

NumPy stands for Numerical Python, is an open-source Python library that provides support for large, multi-dimensional arrays and matrices.

It also have a collection of high-level mathematical functions to operate on arrays. It was created by Travis Oliphant in 2005.

<h2 style = "color : #FF6700"> What is NumPy? </h2>

NumPy is a general-purpose array-processing package.

It provides a high-performance multidimensional array object and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It is open-source software. 

<h2 style = "color : #FFBF00"> Features of Numpy </h2>

NumPy has various features which make them popular over lists.

Some of these important features include:

- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

* Besides its obvious scientific uses, NumPy in Python can also be used as an efficient multi-dimensional container of generic data.

* Arbitrary data types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

<h3 style = " color :#3B9C9C"> Install Python Numpy </h3>

In [15]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


<h3 style = "color : #00FFFF"> Import Numpy Library </h3>

In [19]:
import numpy as np

In [29]:
l1 = [10, 20, 30]
print('List 1 : ', l1)

List 1 :  [10, 20, 30]


In [25]:
np.array(l1)

array([10, 20, 30])

In [31]:
l2 = [10, 20, "30"]
print('List 2 : ', l2)

List 2 :  [10, 20, '30']


In [35]:
np.array(l2)

array(['10', '20', '30'], dtype='<U11')

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
a1 = np.ones(5, int)
a1

array([1, 1, 1, 1, 1])

In [57]:
a1[2] = "xyz"

ValueError: invalid literal for int() with base 10: 'xyz'

In [59]:
a1[2] = 2

In [61]:
a1

array([1, 1, 2, 1, 1])

In [63]:
a_1 = np.zeros(10)
a_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
type(a_1)

numpy.ndarray

In [69]:
a_1.dtype

dtype('float64')

In [71]:
a_2 = np.zeros(10, int)
a_2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
a_2.dtype

dtype('int32')

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

<h2 style = "color : #FF6700"> Arrays in NumPy </h2>

NumPy’s main object is the homogeneous multidimensional array.

- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- In NumPy, dimensions are called axes. The number of axes is rank.
- NumPy’s array class is called ndarray. It is also known by the alias array.

In [85]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
l3 = [1, 2, 3, 4]
l3

[1, 2, 3, 4]

In [91]:
a2 = np.array(l3)
a2

array([1, 2, 3, 4])

In [93]:
a3 = a2.reshape(2, 2)
a3

array([[1, 2],
       [3, 4]])

In [95]:
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

<h2 style = "color : tomato"> NumPy Array Creation </h2>

<h3 style = "color : coral"> 1. Create NumPy Array with List and Tuple </h3>

In [106]:
# Creating array from list with type float
a4 = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print("Array created using list:\n", a4)

# Creating array from tuple
a5 = np.array((1 , 3, 2))
print("\nArray created using tuple:\n", a5)

Array created using list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using tuple:
 [1 3 2]


<h3 style = "color : coral"> 2. Create Array of Fixed Size </h3>

Often, the element is of an array is originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content.

This minimize the necessity of growing arrays, an expensive operation. For example: np.zeros, np.ones, np.full, np.empty, etc.

To create sequences of numbers, NumPy provides a function analogous to the range that returns arrays instead of lists.

In [111]:
# Creating a 3X4 array with all zeros
A1 = np.zeros((3, 4))
print("An array initialized with all zeros:\n", A1)

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [113]:
A1.shape

(3, 4)

In [123]:
A1[2] = 1

In [125]:
A1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [127]:
A1[2,1] = 2

In [129]:
A1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 2., 1., 1.]])

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

**numpy.full(shape, fill_value, dtype = None, order = ‘C’) : Return a new array with the same shape and type as a given array filled with a fill_value.**

Parameters :

- shape      : Number of rows
- order      : C_contiguous or F_contiguous
- dtype      : [optional, float(by Default)] Data type of returned array.  
- fill_value : [bool, optional] Value to fill in the array.


In [133]:
# Create a constant value array of complex type
A2 = np.full((3, 3), 6, dtype = 'complex')
print("An array initialized with all 6s. " 
            "Array type is complex:\n", A2)

An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [149]:
np.full((5,4), 3, dtype = 'float')

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

***numpy.random.random() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).***


- Syntax  :  numpy.random.random(size=None)

- Parameters : 

- size   :  [int or tuple of ints, optional] Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

- Return  :  Array of random floats in the interval [0.0, 1.0). or a single such random float if size not provided.


In [170]:
# Create an array with random values
A3 = np.random.random((2, 2))
print("A random array:\n", A3)

A random array:
 [[0.16625293 0.64960002]
 [0.91754804 0.36225147]]


In [172]:
A3.ndim

2

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

<h3 style = "color : coral"> 3. Create Using arange() Function </h3>

***The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop)***

Parameters : 

- start : [optional] start of interval range. By default start = 0
- stop  : end of interval range
- step  : [optional] step size of interval. By default step size = 1,  
For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. 
- dtype : type of output array

Return: 

- Array of evenly spaced values.
- Length of array being generated  = Ceil((Stop - Start) / Step) 

***arange():*** This function returns evenly spaced values within a given interval. Step size is specified.

In [174]:
# Create a sequence of integers 
# from 0 to 30 with steps of 5
A4 = np.arange(0, 30, 5)
print("A sequential array with steps of 5:\n", A4)

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

<h3 style = "color : coral"> 4. Create Using linspace() Function </h3>

<h4 style = "color : cyan"> The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop]. </h4>

<h4 style = "color : cyan"> It is similar to NumPy.arange() function but instead of a step, it uses a sample number. </h4>

<b style = "color : darkorange"> Syntax </b>


<b>Synatx:</b> numpy.linspace(start, stop, num=50, endpoint=True , retstep=False, dtype=None, axis=0)

<b>Parameters:</b>


- start: [optional] start of interval range. By default start = 0

- stop: end of interval range

- num: [int, optional] No. of samples to generate

- retstep: If True, Stop is the last sample By default restep = False

- endpoint: If True, stop is included as the last value. If False, stop is excluded. By default  endpoint=True.

- dtype: type of output array

- axis: If start and stop are arrays, axis specifies on what axis will the values be added. If axis = 0, value is added to front, if  axis = -1 value is added at the end.


In [194]:
# Create a sequence of 10 values in range 0 to 5
A5 = np.linspace(0, 5, 10)
print("A sequential array with 10 values between 0 and 5:\n", A5)

A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

<h3 style = "color : coral"> 5. Reshaping Array using Reshape Method </h3>

**Reshaping array:** We can use reshape method to reshape an array.

Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM. (i.e. the original size of the array remains unchanged.)

In [198]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print("Original array:\n", arr)
print("---------------")
print("Reshaped array:\n", newarr)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
---------------
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

<h3 style = "color : coral"> 6. Flatten Array </h3>

**Flatten array:** We can use flatten method to get a copy of the array collapsed into one dimension.

It accepts order argument. The default value is ????’ (for row-major order). Use ????’ for column-major order.

In [204]:
# Flatten array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr1.flatten()

print("Original array:\n", arr1)
print('-------------------------')
print("Fattened array:\n", flat_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
-------------------------
Fattened array:
 [1 2 3 4 5 6]


-----------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------

<h2 style = "color : steelblue"> NumPy Array Indexing </h2>

<b style = "color : tomato"> NumPy Array Indexing </b>

Knowing the basics of NumPy array indexing is important for analyzing and manipulating the array object. 
NumPy in Python offers many ways to do array indexing.

- Slicing: Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify
a slice for each dimension of the array.

- Integer array indexing: In this method, lists are passed for indexing for each dimension. One-to-one mapping of corresponding
elements is done to construct a new arbitrary array.

- Boolean array indexing: This method is used when we want to pick elements from the array which satisfy some condition.

In [213]:
# Python program to demonstrate
# indexing in numpy

# An exemplar array
arr_1 = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Slicing array
temp = arr_1[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

# Integer array indexing example
temp = arr_1[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp)

# boolean array indexing example
arr_2 = arr_1 > 0 # arr_2 is a boolean array
temp = arr_1[arr_2]
print("\nElements greater than 0:\n", temp)


Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [215]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [217]:
arr1.max()

6

In [219]:
arr1.sum()

21

In [221]:
arr1.cumsum()

array([ 1,  3,  6, 10, 15, 21])

In [231]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [229]:
arr4 = arr1 + 7
arr4

array([[ 8,  9, 10],
       [11, 12, 13]])

In [233]:
arr5 = arr1 * 7
arr5

array([[ 7, 14, 21],
       [28, 35, 42]])